# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SinFP
version:      1.02
version_from: lib/Net/SinFP.pm
installdirs:  site
requires:
    Class::Gomor:                  0
    DBIx::SQLite::Simple:          0.32
    Net::Packet:                   2.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
